// <auto-generated />
namespace NinjaDomain.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Adddateofbirthtoninja : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adddateofbirthtoninja));
        
        string IMigrationMetadata.Id
        {
            get { return "201709042358149_Add-date-of-birth-to-ninja"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
